# NumPy: 배열과 벡터 계산

### NumPy Documentation

[Tutorials](https://docs.scipy.org/doc/numpy/index.html)

#### Numerical Python의 줄임말

1. 빠르고 효율적인 메모리 사용, 벡터 연산, 브로드캐스팅(확대) 기능을 제공하는 다차원 배열인 ndarray (n dimentional array)를 제공
1. for 문 등 반복문을 작성할 필요없이 전체 배열에 대해 빠른 연산을 제공
1. 배열 데이터를 디스크에 쓰거나 읽을 수 있는 도구
1. 선형대수, 난수 발생기, 푸리에(Fourier) 변환 기능
1. C, C++, 포트란 등 다른 언어로 쓰여진 코드를 통합하는 도구

#### 데이터 분석에서 빠른 연산을 위해 자주 사용하는 기능

1. 배열에서 데이터 변경, 정제, 부분 집합, 필터링의 빠른 수행
2. 정렬, 유일 원소 찾기, 집합 연산
3. 통계 표현과 데이터의 수집/요약
4. 여러 데이터의 병합, 데이터 정렬과 데이터 조작

#### 표준 NumPy의 컨벤션을 import numpy as np로 사용

---

## 1. NumPy ndarray: 다차원 배열 객체

### 1.1 ndarray 사용

In [1]:
import numpy as np 

In [2]:
lst = [1, -2, -3, 4,  5,  6]
lst

[1, -2, -3, 4, 5, 6]

In [3]:
arr = np.array(lst)
arr

array([ 1, -2, -3,  4,  5,  6])

In [4]:
arr * 3

array([ 3, -6, -9, 12, 15, 18])

In [5]:
arr + arr

array([ 2, -4, -6,  8, 10, 12])

#### <참고> 파이썬 리스트의 산술 연산

In [6]:
lst * 3

[1, -2, -3, 4, 5, 6, 1, -2, -3, 4, 5, 6, 1, -2, -3, 4, 5, 6]

In [7]:
lst + lst

[1, -2, -3, 4, 5, 6, 1, -2, -3, 4, 5, 6]

### 1.2 ndarray 생성

In [8]:
# 1차원 배열
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1


array([6. , 7.5, 8. , 0. , 1. ])

In [9]:
# 2차원 배열
data2 = [[1,2,3,4], [5,6,7,8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
print(arr1.shape)
print(arr2.shape)

(5,)
(2, 4)


In [11]:
print(arr1.ndim)
print(arr2.ndim)

1
2


#### 차원 변경 : reshape(), ravel(), flatten()

In [12]:
arr2.reshape((4,2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [13]:
# 다차원 배열을 1차원 배열로 평평하게 펴주는 NumPy의 ravel() 함수
arr2.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
# 다차원 배열을 1차원 배열로 평평하게 펴주는 NumPy의 flatten() 함수, 사본을 생성
arr2.flatten()   

array([1, 2, 3, 4, 5, 6, 7, 8])

#### <참고> np.array는 생성될 때 적절한 자료형을 선택한다.

In [15]:
print(arr1.dtype)
print(arr2.dtype)

float64
int64


#### np.zeros(): 0 으로 초기화된 배열 생성

In [16]:
np.zeros(10) 

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
np.zeros((3,6)) ## 3행 6열

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

#### np.eye()/np.identity() : 대각선이 1인 2차 행렬

In [18]:
np.eye((3)) ## 3행 3열

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.identity((3)) ## 3행 3열

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### np.empty(): 초기화 되지 않은 배열 생성

In [20]:
np.empty((2,5)) 

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### np.arange(): 파이썬 range() 함수의 배열 버전

In [21]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

함수| 설명
:---| :---
array | 입력 데이터(리스트, 튜플, 배열 또는 다른 순차형 데이터)를 ndarray로 변환하며 dtype이 명시되지 않은 경우에는 자료형을 추론하여 저장한다. 기본적으로 입력 데이터는 복사된다.
asarray | 입력 데이터를 ndarray로 변환하지만 입력 데이터가 이미 ndarray일 경우, 복사가 되지 않는다.
arange | 내장 range 함수와 유사하지만 리스트 대신 ndarray를 반환한다.
ones, ones_like | 주어진 dtype과 주어진 모양을 가지는 배열을 생성하고 내용을 모두 1로 초기화한다. ones_like는 주어진 배열과 동일한 모양과 dtype을 가지는 배열을 새로 생성하여 내용을 모두 1로 초기화한다.
zeros, zeros_like | ones, ones_like와 같지만 내용을 0으로 채운다.
empty, empty_like | 메모리를 할당하여 새로운 배열을 생성하지만 ones나 zeros처럼 값을 초기화하지는 않는다.
eye, identity | N x N 크기의 단위 행렬을 생성한다(좌상단에서 우하단을 잇는 대각선은 1로 채워지고 나머지는 0으로 채워진다).

### 1.3 ndarray의 자료형

dtype로 자료형을 알 수 있다.

- 산술 데이터의 dtype은 float, int 같은 자료형의 이름과 하나의 원소가 차지하는 비트로 이루어짐
- 파이썬의 float 객체에서 사용되는 부동소수점 값은 8바이트 혹은 64바이트로 이루어짐
- [NumPy 자료형](http://docs.scipy.org/doc/numpy/user/basics.types.html)

In [22]:
arr1 = np.array([1,2,3], dtype=np.float32)
arr1

array([1., 2., 3.], dtype=float32)

In [23]:
arr2 = np.array([1,2,3], dtype=np.float64)
arr2

array([1., 2., 3.])

In [24]:
arr1.dtype, arr2.dtype

(dtype('float32'), dtype('float64'))

#### 타입 변경:  astype() 메소드

In [25]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [26]:
arr.dtype

dtype('int64')

In [27]:
float_arr = arr.astype(np.float64)
float_arr

array([1., 2., 3., 4., 5.])

In [28]:
float_arr.dtype

dtype('float64')

In [29]:
arr.dtype

dtype('int64')

In [30]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [31]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [32]:
num_str = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [33]:
num_str

array([b'1.25', b'-9.6', b'42'], dtype='|S4')

In [34]:
num_str.astype(float) 

array([ 1.25, -9.6 , 42.  ])

#### <참고> dtype 축약코드

종류 | Type Code | 설명
:---|:---|:---
int8,  uint8  | i1, u1   | 부호가 있는 8비트(1바이트) 정수형과 부호가 없는 8비트 정수형
int16, uint16 | i2, u2   | 부호가 있는 16비트 정수형과 부호가 없는 16비트 정수형
int32, uint32 | i4, u4   | 부호가 있는 32비트 정수형과 부호가 없는 32비트 정수형
int64, uint64 | i8, u8   | 부호가 있는 64비트 정수형과 부호가 없는 64비트 정수형
float16       | f2       | 반정밀도 부동소수점
float32       | f4 or f  | 단정밀도 부동소수점 C 언어의 float 형과 호환
float64       | f8 or d  | 배정밀도 부동소수점 C 언어의 double 형과 파이썬의 float 객체와 호환
float128      | f16 or g | 확장 정밀도 부동소수점
bool          | ?        | True, False 값을 저장하는 불리언형
object        | O        | 파이썬 객체형
string_       | S        | 고정 길이 문자열형, 길이가 10인 문자열의 dtype은 S10
unicode_      | U        | 고정 길이 유니코드형(예: U10)


In [35]:
emp_uint32 = np.empty(8, dtype='u4')
emp_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

### 1.4 배열과 스칼라 간의 연산

- **배열은 for 반복문을 작성하지 않고 데이터를 일괄처리할 수 있다(벡터화)**
- 같은 크기의 배열 간 산술연산은 배열의 각 요소 단위로 적용

In [36]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [37]:
arr * 3

array([[ 3.,  6.,  9.],
       [12., 15., 18.]])

In [38]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [39]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [40]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [41]:
# **는 square root of x
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

### 1.5 인덱싱(색인)과 슬라이싱

In [42]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
arr[5]

5

In [44]:
arr[5:8] 

array([5, 6, 7])

In [45]:
arr[5:8] = 12

In [46]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

#### 브로드캐스팅
- arr[5:8] = 배열에 스칼라 값을 대입하면 이 값이 필요한 만큼 복사되어 확산 전파
- 파이썬 리스트는 브로드캐스팅 불가

#### 배열 조각은 원본 배열의 View를 리턴 (파이썬 리스트의 슬라이싱은 복사본을 리턴)

- 즉, 데이터는 복사되지 않으며 뷰에 대한 변경은 그대로 원본 배열에 반영
- 복사본이 필요할 경우 arr[5:8].copy()를 사용

#### Slicing : 사용 예

- [:]: 배열 전체
- [0:n]: 0번째부터 n-1번째까지, 즉 n번 항목은 포함하지 않는다.
- [:5]: 0번째부터 4번째까지,5번은 포함하지 않는다.
- [2:]: 2번째부터 끝까지
- [-1]: 제일 끝에 있는 배열값 반환
- [-2]: 제일 끝에서 두번째 값 반환

In [47]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
arr_cp = arr[5:8].copy()

In [49]:
arr_cp[:] = 128
arr_cp

array([128, 128, 128])

In [50]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 2차원, 3차원 배열 제어

In [51]:
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [52]:
arr2d.ndim

2

In [53]:
arr2d[2]

array([7, 8, 9])

In [54]:
arr2d[0][2]

3

In [55]:
# ,로도 구분 가능
arr2d[0, 2]

3

In [56]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [57]:
arr3d.ndim

3

In [58]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
arr_org = arr3d[0].copy()
arr_org

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
arr3d[0] = 42

In [61]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [62]:
arr3d[0] = arr_org

In [63]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [64]:
arr3d[1, 0]

array([7, 8, 9])

#### 슬라이스 색인

In [65]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
arr[1:6]

array([1, 2, 3, 4, 5])

In [67]:
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

#### arr2d[:2, 1:]
     행,  열

- 같은 [ ] 안에서는 행과 열 구분

In [69]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [70]:
arr2d[:2][1:]

array([[4, 5, 6]])

In [71]:
arr2d[1, :2]

array([4, 5])

In [72]:
arr2d[2, :1]

array([7])

In [73]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [74]:
arr2d[:2, 1:] = 0

In [75]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

### 1.6 불리언 색인

In [76]:
data = np.arange(28)
data=data.reshape(7,4)

In [77]:
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27]])

In [78]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [79]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [80]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [81]:
data[names == 'Bob']

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])

In [82]:
names2 = np.array(['Bob', 'Joe', 'Will'])

In [83]:
names2 == 'Bob'

array([ True, False, False])

In [84]:
# data와 boolean 색인 결과와 차원이 달라서 error 발생
data[names2 == 'Bob']

IndexError: boolean index did not match indexed array along dimension 0; dimension is 7 but corresponding boolean dimension is 3

In [ ]:
data[names == 'Bob', 2:]

In [ ]:
data[names == 'Bob', 3]

#### != ,  ~ 으로 부정

In [ ]:
names != 'Bob'

In [ ]:
data[~(names == 'Bob')]

In [ ]:
names

In [ ]:
mask = (names == 'Bob') | (names == 'Will')

In [ ]:
mask

In [ ]:
data[mask]

In [ ]:
data[mask, 3:]

#### 불리언 색인시 항상 데이터 복사

- 파이썬 예약어인 and, or는 불리언 배열에서는 사용 불가

In [ ]:
data[data < 5] = 0

In [ ]:
data

In [ ]:
data[names == 'Bob'] = 7

In [ ]:
data

### 1.7 팬시 색인

In [ ]:
arr = np.empty((8, 4))

In [ ]:
for i in range(8):
    arr[i] = i

In [ ]:
arr

In [ ]:
# 특정한 순서로 로우 선택
arr[[4, 3, 0, 6]]

In [ ]:
arr[[-2, -3]]

In [ ]:
np.arange(32)

In [ ]:
arr = np.arange(32).reshape((8, 4))

In [ ]:
arr

In [ ]:
# 1개 항목을 선택
# (1, 0), (5, 3), (7, 1), (2, 2)에 대응하는 요소가 선택
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

In [ ]:
# 특정 행들을 선택하고 이의 열의 순서를 바꾸는 경우
# 1, 5, 7, 2 행을 선택
# 컬럼 열에서 :,로 모든 행을 선택해 주어야 한다.
# 0, 3, 1, 2 열을 순서대로 선택

arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

In [ ]:
# np.ix_ 사용하는 방법
arr[np.ix_([1, 5, 7, 2], [0, 3, 1, 2])]

### 1.8 배열 전치와 축 바꾸기

In [ ]:
arr = np.arange(15).reshape((3, 5))
arr

In [ ]:
arr.T # 행과 열을 바꿔준다.

In [ ]:
arr.transpose() # T와 같은 역할을 한다.

In [ ]:
arr = np.random.randn(6, 3)
arr

In [ ]:
arr.T

In [ ]:
np.dot(arr.T, arr) # arr.T 3 * 6 행렬 곱하기 arr 6 * 3 행렬의 결과값이다.

---

## 2. 유니버설 함수

- ufunc 유니버설 함수는 ndarray 안에 있는 데이터 원소별로 연산을 수행하는 함수
- 유니버설 함수는 하나 이상의 스칼라 값을 받아서 하나 이상의 스칼라 결과 값을 반환하는 간단한 함수를 고속으로 수행할 수 있는 벡터화된 래퍼 함수

### 2.1 단항 유니버설 함수

In [ ]:
import numpy as np 

In [ ]:
arr = np.arange(10)

In [ ]:
np.sqrt(arr)

In [ ]:
arr

In [ ]:
np.exp(arr)

### 2.2 이항 유니버설 함수

In [ ]:
x = np.random.randn(8)

In [ ]:
y = np.random.randn(8)

In [ ]:
x

In [ ]:
y

In [ ]:
np.maximum(x, y)

#### [Universal functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html)

---

## 3. 배열을 사용한 데이터 처리

- 반복문 작성하지 않고 간결한 배열연산을 통해 많은 종류의 데이터 처리 작업
- **벡터화:** 배열연산을 사용해서 반복문을 명시적으로 제거하는 기법
- 순수 파이썬보다 2~3배, 많게는 수십, 수백 배까지 빠르다.
- **브로드캐스팅:** 아주 강력한 벡터 연산 방법

### 3.1 벡터화

In [ ]:
import numpy as np 

In [ ]:
points = np.arange(1000000, dtype='f')
points[:10]

### :- for 문과 배열연산의 누적값 처리 시간 비교

In [ ]:
# sum using for loop
%time
total = 0
for i in points:
    total += i
print(total)

In [ ]:
# sum using array
%time points.sum()

### 3.2 배열연산으로 조건절 표현하기

In [ ]:
xarr = np.array([1, 2, 3, 4, 5])
yarr = np.array([6, 7, 8, 9, 10])
cond = np.array([True, False, True, False, True])

In [ ]:
result = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]
result

### - where () 함수
- 조건이 참이면 x의 원소를, 거짓이면 y의 원소로 하는 벡터를 반환.
- 'x if condition else y'를 벡터화시킨 것.

In [ ]:
# 위와 같은 결과
result = np.where(cond, xarr, yarr)
result

### 3.3 수학 메서드와 통계 메서드

In [ ]:
arr = np.array([[1,1,1,1],
               [2,2,2,2],
               [3,3,3,3],
               [4,4,4,4],
               [5,5,5,5]])
#random.randn(5, 4)
arr

In [ ]:
arr.shape

In [ ]:
arr.mean()

In [ ]:
np.mean(arr)

In [ ]:
arr.sum()

#### 연산을 진행할 축을 선택( 행방향: axis = 0, 열방향: axis = 1) - Default: axis = 0
#### <참고> axis = 0:행방향 연산, 세로로 연산, 같은 컬럼 끼리 연산

In [ ]:
# 행렬의 열 방향으로의 합, 즉 같은 컬럼의 합
arr.sum(axis=0)

In [85]:
arr.sum(0)

45

In [86]:
# 행렬의 행 방향으로의 합
arr.sum(axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [ ]:
arr.sum(1)

In [ ]:
arr.mean(axis=1)

#### 누적연산 - cumsum(), cumprod(): 중간 계산 값을 담고 있는 배열을 반환

In [ ]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr

In [ ]:
arr.cumsum(axis=0)

In [ ]:
arr.cumprod(axis=1)

In [ ]:
arr.cumprod(axis=0)

#### 기본 배열 통계 메서드

메세드 | 설명
:---|:---
sum            | 배열 전체 혹은 특정 축에 대한 모든 원소의 합을 계산한다.
mean           | 산술평균을 구한다. 크기가 0인 배열에 대한 mean 결과는 NaN이다.
std, var       | 각각 표준편차와 분산을 구한다.
min, max       | 최소값, 최대값
argmin, argmax | 최소 원소의 색인 값, 최대 원소의 색인 값
cumsum         | 각 원소의 누적 합
cumprod        | 각 원소의 누적 곱


### 3.4 불리언 배열을 위한 메서드

- 불리언 값은 True = 1, False = 0 으로 취급
- 불리언 배열에 대한 sum 메서드를 실행하면 True인 원소의 개수를 반환

In [ ]:
arr = np.random.randn(100)
arr

In [ ]:
(arr > 0).sum()

In [ ]:
arr[:10]

In [ ]:
bools = np.array([False, False, True, False])

In [ ]:
# 하나라도 True 이면 결과는 True
bools.any()

In [ ]:
# 모두 True 이면 결과는 True
bools.all()

In [ ]:
bools = np.array([True, True, True, True])

In [ ]:
bools.any()

In [ ]:
bools.all()

#### 배열의 값이 0 이면 False, 그 외 나머지는 모두 True로 취급

In [ ]:
arr.any()

In [ ]:
arr.all()

### 3.5 정렬

In [ ]:
arr = np.random.randn(8)
arr

In [ ]:
# <참고> 원본을 변경하지 않음
np.sort(arr)

In [ ]:
arr

In [ ]:
# 원본을 변경함
arr.sort()
arr

#### 다차원 배열의 정렬

In [ ]:
arr = np.random.randn(5, 3)
arr

In [ ]:
# axis = 0: 세로방향 정렬(column sort)
arr.sort(axis=0)
arr

In [ ]:
# axis = 1: 가로방향 정렬(row sort)
arr.sort(axis=1)
arr

### 3.6 배열의 집합함수

In [ ]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

#### 중복제거

In [ ]:
np.unique(names)

In [ ]:
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])

In [ ]:
np.unique(ints)

In [ ]:
# 집합을 이용한 중복제거
unique_set = set(names)
unique_arr = np.array(unique_set)
unique_arr


#### np.in1d()

In [ ]:
values = np.array([6, 0, 0, 3, 2, 5, 6])
values

In [ ]:
np.in1d(values, 2)

In [ ]:
np.in1d(values, [2, 3, 6])

#### 배열 집합 연산

Method | Comment
:---|:---
unique(x)         | 배열 x에서 중복된 원소를 제거한 후 정렬하여 반환한다.
intersect1d(x, y) | 배열 x와 y에 공통적으로 존재하는 원소를 정렬하여 반환한다.
union1d(x, y)     | 두 배열의 합집합을 반환한다.
in1d(x, y)        | x의 원소 중 y의 원소를 포함하는지를 나타내는 불리언 배열을 반환한다.
setdiff1d(x, y)   | x와 y의 차집합을 반환한다.
setxor1d(x, y)    | 한 배열에는 포함되지만 두 배열 모두에는 포함되지 않는 원소들의 집합인 대칭차집합을 반환한다.

---

## 4. 배열의 파일 입∙출력

### 4.1 배열을 바이너리 형식으로 디스크에 저장하기

In [ ]:
import numpy as np

arr1 = np.arange(10)

In [ ]:
arr2 = np.arange(5)

In [ ]:
np.save('data/file_arr1.npy', arr1)

In [87]:
arr1_l = np.load('data/file_arr1.npy')
arr1_l

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
# 압축해서 저장
np.savez('data/array_archive.npz', a=arr1, b=arr2)

In [89]:
arch = np.load('data/array_archive.npz')

In [90]:
arch['a']

array([1., 2., 3.], dtype=float32)

In [91]:
arch['b']

array([1., 2., 3.])

### 4.2 텍스트 파일 불러오기와 저장하기

In [92]:
arr = np.array( [[2.23342715,-0.37376633,-1.05142871],
                 [-0.57247149,-1.35777871,0.28676036],
                 [-0.01042671,-0.0211314,-0.72049352]])

In [93]:
arr

array([[ 2.23342715, -0.37376633, -1.05142871],
       [-0.57247149, -1.35777871,  0.28676036],
       [-0.01042671, -0.0211314 , -0.72049352]])

In [94]:
np.savetxt('data/array_ex.txt', arr, delimiter=',')

In [95]:
arr_l = np.loadtxt('data/array_ex.txt', delimiter=',')

In [96]:
arr_l

array([[ 2.23342715, -0.37376633, -1.05142871],
       [-0.57247149, -1.35777871,  0.28676036],
       [-0.01042671, -0.0211314 , -0.72049352]])

---

## 5. 선형대수

In [97]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])

In [98]:
y = np.array([[6., 23.], [-1, 7], [8, 9]])

In [99]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [100]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [101]:
x.shape


(2, 3)

In [102]:
y.shape

(3, 2)

In [103]:
# np.dot(x, y)
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [104]:
arr=np.array(range(1,10)).reshape((3,3))
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [105]:
a = arr[0:, 1:]
a

array([[2, 3],
       [5, 6],
       [8, 9]])

In [106]:
a = np.array(range(1,13)).reshape(3,4)
a
s=a[[0,2],[1,3]]
print(s)

lst=list(range(1,13))
lst

[ 2 12]


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [107]:
lst = list(range(1,10))
lst
a = np.array(lst).reshape(3,3)
a
bool_indexing_array = np.array([[False, True, False],[True,False, True],[False, True, False]])
n = a[bool_indexing_array]
print(n)
bool_indexing = (a  % 2  ==  1)
print( bool_indexing)
n = a[a % 2 == 1]
print(n)


[2 4 6 8]
[[ True False  True]
 [False  True False]
 [ True False  True]]
[1 3 5 7 9]


In [108]:
from numpy.linalg import inv

In [109]:
X = np.random.randn(5, 5)

In [110]:
mat = X.T.dot(X)

In [111]:
mat

array([[ 3.14269535, -3.05643864,  0.68397752,  0.4256556 ,  1.26919127],
       [-3.05643864, 10.9817626 , -0.38910268, -4.70041212,  3.54527393],
       [ 0.68397752, -0.38910268, 10.7146655 ,  3.68062843, -1.05298843],
       [ 0.4256556 , -4.70041212,  3.68062843,  5.79030434, -5.40033681],
       [ 1.26919127,  3.54527393, -1.05298843, -5.40033681,  8.27145385]])

In [112]:
inv(mat)  # 행렬을 역행렬으로 변환

array([[ 0.66919681,  0.23408551, -0.03156763, -0.08232167, -0.26078138],
       [ 0.23408551,  0.26748963, -0.10114087,  0.28583891,  0.02317644],
       [-0.03156763, -0.10114087,  0.19618366, -0.34838229, -0.15428547],
       [-0.08232167,  0.28583891, -0.34838229,  1.24882719,  0.66111106],
       [-0.26078138,  0.02317644, -0.15428547,  0.66111106,  0.56296949]])

In [113]:
# 행렬 * 역행렬 = 단위 행렬
mat.dot(inv(mat))

array([[ 1.00000000e+00,  3.01524467e-17,  1.65602567e-17,
         4.67063506e-18,  4.16795450e-18],
       [ 3.55789890e-16,  1.00000000e+00, -6.87747404e-18,
        -5.17093894e-16, -3.75791955e-17],
       [-4.42110670e-17, -1.75276744e-16,  1.00000000e+00,
        -6.44837403e-16, -1.80163935e-16],
       [ 2.04557656e-16,  1.23642365e-16, -2.01993600e-16,
         1.00000000e+00,  1.43308520e-16],
       [-1.10730167e-17,  1.49684668e-16,  2.18190978e-16,
        -7.08313310e-16,  1.00000000e+00]])

## 6. 난수 생성

In [114]:
samples = np.random.normal(size=(4, 4))

In [115]:
samples

array([[-1.05503926,  2.20211239, -0.10524502,  0.01397461],
       [-0.73510374,  0.19743406, -0.90190219, -1.38263594],
       [ 0.3768152 ,  0.08573479, -0.46413281,  0.27419493],
       [ 1.01072279,  0.3045105 , -1.29238031, -0.98739465]])

In [116]:
import random

In [117]:
N = 1000000

In [118]:
%time samples = [random.normalvariate(0, 1) for _ in range(N)]

CPU times: user 645 ms, sys: 19.9 ms, total: 665 ms
Wall time: 685 ms


In [119]:
samples[:10]

[-0.36742550476001423,
 -0.30160867895119464,
 0.18556027323537747,
 1.0397621160851882,
 0.3903146415047531,
 1.5552081102828397,
 -0.22396904481482832,
 -0.13794656118975981,
 -1.3587251165427523,
 -0.17235313419633222]

In [120]:
%time samples_arr = np.random.normal(size=N)

CPU times: user 27.5 ms, sys: 3.06 ms, total: 30.5 ms
Wall time: 30.9 ms


In [121]:
samples_arr[:10]

array([ 0.36193333, -1.71178811,  0.4578726 , -0.3039742 , -0.74475724,
       -0.91575948, -0.07966712, -0.02962003, -0.32411908,  0.6377038 ])

#### numpy.random 함수

함수 | 설명
:---|:---
seed        | 난수 발생기의 시드를 지정한다.
permutation | 순서를 임의로 바꾸거나 임의의 순열을 반환한다.
shuffle     | 리스트나 배열의 순서를 뒤섞는다.
rand        | 균등분포에서 표본을 추출한다.
randint     | 주어진 최소/최대 범위 안에서 임의의 난수를 추출한다.
randn       | 표준편차가 1이고 평균 값이 0인 정규분표에서 표본을 추출한다.
binomial    | 이항분포에서 표본을 추출한다.
mormal      | 정규분포에서 표본을 추출한다.
beta        | 베타분포에서 표본을 추출한다.
chisquare   | 카이제곱분포에서 표본을 추출한다.
gamma       | 감마분포에서 표본을 추출한다.
uniform     | 균등(0,1)분포에서 표본을 추출한다.


---