## Python은 독해력, 단순함 및 명료성에 중점을 둡니다.

* 모든 것은 파이썬의 객체(object)입니다. 
* 모든 숫자, 문자열, 데이터 구조, 클래스를 파이썬 객체라고합니다.


### 1. Python Coding Basic

### - 코딩블럭 들여쓰기(indentation)
- 파이쎤은 코딩블럭을 표시하기 위해 들여쓰기를 사용한다.
- 코딩블럭을 시작하는 문장들(if, for, def)

In [1]:
import datetime

dt = datetime.datetime.now()
print("now : ", dt)

if dt.hour >= 12:
    print("PM")
else:
    pirnt("AM")

now :  2019-04-08 14:48:11.987076
PM


### - import 
#### 1) import 모듈명

In [2]:
import math
n = math.sqrt(4.0)
print(n)

2.0


#### 2) import  모듈명 as 

In [3]:
# array의 객체 정보를 출력
def pprint(arr):
    print("\ntype:{}".format(type(arr)))
    print("shape: {}, dimension: {}, dtype:{}".format(arr.shape, arr.ndim, arr.dtype))
    print("Array's Data:\n", arr)

In [4]:
import numpy as np

arr = [1, 2, 3]
print(type(arr))

# 1차원 배열
a = np.array(arr)
pprint(a)

# 2차원 배열
arr = [(1,2,3), (4,5,6)]
b= np.array(arr, dtype = float)
pprint(b)
#b= np.array(['spring', 'summer', 'fall', 'winter'])

# 3차원 배렬
c = np.array([[[1,2,3], [4,5,6]], [[3,2,1], [4,5,6]]], dtype = float)
pprint(c)
print("\n == np.ifno of c ==\n")
np.info(c)

<class 'list'>

type:<class 'numpy.ndarray'>
shape: (3,), dimension: 1, dtype:int64
Array's Data:
 [1 2 3]

type:<class 'numpy.ndarray'>
shape: (2, 3), dimension: 2, dtype:float64
Array's Data:
 [[1. 2. 3.]
 [4. 5. 6.]]

type:<class 'numpy.ndarray'>
shape: (2, 2, 3), dimension: 3, dtype:float64
Array's Data:
 [[[1. 2. 3.]
  [4. 5. 6.]]

 [[3. 2. 1.]
  [4. 5. 6.]]]

 == np.ifno of c ==

class:  ndarray
shape:  (2, 2, 3)
strides:  (48, 24, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x7f8c3c997980
byteorder:  little
byteswap:  False
type: float64


#### 3) from 모듈명 import 함수, 변수

In [5]:
from datetime import datetime
start_time = datetime.now()
print("start time : {}".format(start_time))

start time : 2019-04-08 14:48:50.743393


### - dir : 객체가 어떤 변수와 메소드(method)를 가지고 있는지 나열

In [32]:
dir(math)
#dir(datetime)

['__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'ceil',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'e',
 'erf',
 'erfc',
 'exp',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'pi',
 'pow',
 'radians',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'tau',
 'trunc']

### - 코멘트
- 파이썬에서는 코멘트를 표시하기 위하여 '#'를 사용한다.
- 코드에 대한 설명을 하기 위해서 '#'를 사용하지만, 실행하지 않을 코드 앞에 '#'를 넣기도 한다.


In [6]:
# math library를 import
import math
n = math.sqrt(4.0)
#print(n)

### 2. Print

### - 문장을 인쇄하려면 'print' functon을 사용할 수 있습니다.

In [7]:
print("Python lesson")

Python lesson


In [8]:
print('Python lesson')

Python lesson


In [9]:
print("'PYTHON' lesson")

'PYTHON' lesson


In [10]:
print("welcome" "to" "'python world'")
print("welcome", "to", "'python world'")

welcometo'python world'
welcome to 'python world'


###  - 문자열에 '가 포함된 경우는 Syntax Error

In [11]:
print(''PYTHON' lesson')

SyntaxError: invalid syntax (<ipython-input-11-b86adac7a2fa>, line 1)

### - 문자열에 '를 포함한 특수문자를 그대로 표현하고 싶은 경우는 escape character( \'\\\')을 앞에 넣는다

In [13]:
print('\'PYTHON\' lesson')

'PYTHON' lesson


### - 포맷된 형태로 출력

In [14]:
temperature = 22;
humidity = 70;
print("오늘은 온도는 {}도이고, 습도는 {}%입니다".format(temperature, humidity))
print("오늘은 온도는 %d도이고, 습도는 %d%%입니다" % (temperature,humidity))


오늘은 온도는 22도이고, 습도는 70%입니다
오늘은 온도는 22도이고, 습도는 70%입니다


### 3. Python 기본 데이터 타입

<center>타 입|<center>설 명|<center>표현 예
:---|:---|:---
int|정수형 데이터|100
float|소숫점을 포함한 실수|3.14159
bool|참/거짓|True
None|Null과 같은 표현|None
str|문자열|'LG Electronics'


### - Number(숫자 자료형)

In [15]:
print(int(3.14159))           # 3
print(2e3)                # 2000.0
print(float("3.14159"))   # 3.14159
print(float("inf"))       # 무한대
print(float("-inf"))      # -무한대
print(bool(0))            # False. 숫자에서 0만 False
print(bool(-1))           # True
print(bool("False"))      # True
a = None                  # a는 None
print(a)
print(a is None)          # a가 None 이므로 True


3
2000.0
3.14159
inf
-inf
False
True
True
None
True


#### - 숫자형 사칙연산 및 주요 operator

In [16]:
a = 7
b = 4
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%b)
print(a//b)
print(a**b)
print("a+b={}, a-b={}, a*b={}, a/b={}, a%b={}, a//b={}, a**b={}".format(a+b, a-b, a*b, a/b, a%b, a//b, a**b))
print("{}+{}={}, {}-{}={}, {}**{}={},".format(a, b, a+b, a, b, a-b, a, b, a**b))

11
3
28
1.75
3
1
2401
a+b=11, a-b=3, a*b=28, a/b=1.75, a%b=3, a//b=1, a**b=2401
7+4=11, 7-4=3, 7**4=2401,


### - String(문자열 자료형)

In [17]:
welcome_str = "Python Lesson에 오신 것을 환영합니다"
print(welcome_str)

Python Lesson에 오신 것을 환영합니다


In [18]:
lastName = 'Lee'
firstName = 'Younghee'

print("My name is", firstName, lastName)  # Younghee Lee
print( (lastName + ' ') * 5)      # Lee Lee Lee Lee Lee 

My name is Younghee Lee
Lee Lee Lee Lee Lee 


#### -  문자열 더해서 연결하기(Concatenation)

In [19]:
fullName = lastName + " " + firstName
print(fullName)
print(lastName + " " + firstName)

Lee Younghee
Lee Younghee


#### - 문자열 곱하기

In [20]:
count = 5
print("별점(*) : " + "*" * count)

별점(*) : *****


### - indexing string(문자열 인덱싱)

In [21]:
welcome_str = 'Python Lesson'
print(len(welcome_str))
print(welcome_str[0])   # P
print(welcome_str[1])   # y
print(welcome_str[12])  # n

print(welcome_str[-1])  # n
print(welcome_str[-2])  # o

welcome_str2 = '파이썬 레슨'
print(len(welcome_str2))
print(welcome_str2[0])   # 파
print(welcome_str2[1])   # 이
print(welcome_str2[5])   # 슨

print(welcome_str2[-1])  # 슨
print(welcome_str2[-2])  # 레

13
P
y
n
n
o
6
파
이
슨
슨
레


### - slicing string(문자열 스라이싱)

In [22]:
print(welcome_str[0:6])
print(welcome_str2[0:6])

print(welcome_str[6:])
print(welcome_str2[6:])

print(welcome_str[6:-1])
print(welcome_str2[3:-1])


Python
파이썬 레슨
 Lesson

 Lesso
 레


### - Encoding

In [23]:
welcome = "Python Lesson에 오신것을 환영합니다"
print(type(welcome))

<class 'str'>


In [24]:
print(welcome.encode('utf-8'))

b'Python Lesson\xec\x97\x90 \xec\x98\xa4\xec\x8b\xa0\xea\xb2\x83\xec\x9d\x84 \xed\x99\x98\xec\x98\x81\xed\x95\xa9\xeb\x8b\x88\xeb\x8b\xa4'


In [25]:
welcome.encode('utf-8').decode('utf-8')

'Python Lesson에 오신것을 환영합니다'

###  - laTeX

#### - code pane에 표시하는 경우

In [26]:
from IPython.display import display, Math, Latex
display(Math(r'F(k) = \int_{-\infty}^{\infty} f(x) e^{2\pi i k} dx'))


<IPython.core.display.Math object>

#### - markdown pane에 표시하는 경우
$$c = \sqrt{a^2 + b^2}$$